# Extended image: pi-sandbox with the engram learning engine (opencode-engram-learning).
#
# Build (directory builds default to pi-sandbox:base):
#   docker build -f Dockerfile.pi.learn -t pi-sandbox:learn .
#   docker build --build-arg BASE_IMAGE=pi-sandbox:base -f Dockerfile.pi.learn -t pi-sandbox:learn .

ARG BASE_IMAGE=pi-sandbox:base
FROM ${BASE_IMAGE}

RUN pi install npm:opencode-engram-learning
