# Extended image: pi-sandbox with the wiki extension (pi-llm-wiki).
#
# Build (directory builds default to pi-sandbox:base):
#   docker build -f Dockerfile.pi.wiki -t pi-sandbox:wiki .
#   docker build --build-arg BASE_IMAGE=pi-sandbox:base -f Dockerfile.pi.wiki -t pi-sandbox:wiki .

ARG BASE_IMAGE=pi-sandbox:base
FROM ${BASE_IMAGE}

RUN pi install npm:@zosmaai/pi-llm-wiki
